apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret.yaml

replicas:
- name: nginx
  count: 2

generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- name: config
  behavior: create
  files:
  - .env.properties

images:
- name: nginx
  newName: nginx #Should be the image in AWS ECR or whatever registry you want the cloud to pull from
  newTag: 1.25.3 #Should be the tag that was built in CI