apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret.yaml

replicas:
- name: nginx
  count: 1

generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- name: config
  behavior: create
  files:
  - .env.properties

images:
- name: nginx
  newName: public.ecr.aws/nginx/nginx #Should be the image in AWS ECR or whatever registry you want the cloud to pull from
  newTag: stable-perl #Should be the tag that was built in CI