---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
type: Opaque
data:
  atlantis-gh-app-id: <atlantis-gh-app-id>
 